### ISSUE TITLE
sonarqube/0.0.70-rc.1 Support Xenial Stemcell

### ISSUE THREAD

**Issue by Muruganfly03** [FINkit/sonarqube-boshrelease#92]
Hi Team,

I am using sonarqube/0.0.70-rc.1 in our environment which is using stemcell -
bosh-vsphere-esxi-ubuntu-trusty-go_agent/3541.34

Kindly confirm whethersonarqube/0.0.70-rc.1 version support Xenial stemcell?

**Comment by stuart-c-moore** [comment]
Hi @Muruganfly03, this should work, we were using this on xenial internally.

I would like to point out that this boshrelease is very unlikely to receive any further updates, as the FINkit org has been shutdown and therefore has no one actively working on it.
